#!/usr/bin/python
"""
Class (model) file for create_consensus_project
"""

class NucleotideCount(Object):
	def __init__(self, indexNum):
		self.indexNum = indexNum
		self.aCount = 0
		self.cCount = 0
		self.gCount = 0
		self.tCount = 0

